version: 2.0

jobs:
    build:
        docker:
            - image: rust:latest
        steps:
            - checkout
            - run: rustup component add rustfmt-preview
            - run: cargo fmt -- --write-mode=diff
            - run: cargo search  # Update registry outside build process
            - run: cargo build
            - run: cargo build --release
            - setup_remote_docker
            - run:
                name: Build docker container
                command: docker build .
            - store_artifacts:
                path: target/release/circleci-artifact-proxy
                destination: circleci-artifact-proxy
