version: 2.0

jobs:
    build:
        docker:
            - image: rust:latest
        steps:
            - checkout
            - restore_cache:
                keys:
                    - cargo-{{ checksum "Cargo.lock" }}-{{ checksum "rust-toolchain" }}-{{ checksum ".circleci/config.yml" }}
            - run: rustup component add rustfmt-preview
            - run: cargo fmt -- --write-mode=diff
            - run: cargo search  # Update registry outside build process
            - run: cargo build
            - run: cargo build --release
            - store_artifacts:
                path: target/release/circleci-artifact-proxy
                destination: circleci-artifact-proxy
            - save_cache:
                key: cargo-{{ checksum "Cargo.lock" }}-{{ checksum "rust-toolchain" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - /usr/local/cargo
